platform :ios, '10.0'

target 'DeliverPage' do
    use_frameworks!

  # Pods for DeliverPage

pod 'iOSDropDown'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'SideMenu'




  target 'DeliverPageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DeliverPageUITests' do
    # Pods for testing
  end

end
